events {}

http {
  upstream web_cluster {
      server web-frontend-server1:80;
      server web-frontend-server2:80;
  }

  server {
    listen 80;
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

    location / {
      proxy_pass http://web_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
      proxy_pass http://application-backend-server:8081/;
      proxy_set_header Host $host;
    }

    location /student/ {
      proxy_pass http://application-backend-server:8081/student;
      proxy_set_header Host $host;
    }

    location /auth/ {
      proxy_pass http://authentication-identity-server:8080/;
      proxy_set_header Host $host;
    }
  }
}
